-- AlterTable
ALTER TABLE "users" ALTER COLUMN "createdAt" SET DEFAULT '',
ALTER COLUMN "createdAt" SET DATA TYPE TEXT,
ALTER COLUMN "updatedAt" SET DEFAULT '',
ALTER COLUMN "updatedAt" SET DATA TYPE TEXT;
